spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebanking?createDatabaseIfNotExist=true
    username: root
    password: Abhi@180902
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8055